config/routes.rb
Ruvote::Application.routes.draw do

  resources :screens, :only => [:show, :update] do
    member do
      get "banner"
      get "twitts"
      get "question"
    end
  end

  get "home" => 'static#home'
  get 'login/registration' => 'login#registration'
  get 'login/forgot_password' => 'login#forgot_password'
  get 'login/login' => 'login#login'

  resources :s, :only => [:show, :index] do
    member do 
      get 'twitt'
      get 'name'
      post 'set_name'
    end
  end

  resources :votes, :only => [] do
    collection do
      post 'radio'
      post 'check'
    end
  end

  resources :twitts, :only => [:create, :destroy]

  resources :answer_variants, :only => [:show, :edit, :create, :update, :destroy] do
    member do
      post 'bringup'
      post 'bringdown'
    end
  end

  resources :questions, :only => [:show, :edit, :create, :update, :destroy] do
    resources :answer_variants, :only => [:new]
    member do
      post "switch_state"
      post "reset_state"
      post "start_countdown"
    end
  end

  resources :sections, :only => [:show, :edit, :create, :update, :destroy] do
    resources :questions, :only => [:new]
    resource :section_statistics, :only => [:show]
    member do
      get 'twitts_edit'
      get 'twitts'
    end
    collection do
      post '/twitt/:twitt_id/activate' => 'sections#activate_twitt'
    end
  end

  resources :meetings do
    resources :sections, :only => [:new]
  end

  devise_for :users

  root :to => "static#home"

end

app/models/question.rb
class Question < ActiveRecord::Base
  include ApplicationHelper
  after_initialize :set_defaults
  
  attr_accessible :kind, :question, :state, :countdown_to
  belongs_to :section
  has_many :answer_variants, :order => "position asc", :dependent => :destroy
  validates :question, :kind, :state, :presence => true
  validates :question, :uniqueness => {:scope => [:section_id]}
  validates :kind, :inclusion => {:in => %w(radio check)} #stars)}
  validates :state, :inclusion => {:in => %w(new showed active statistics finished)}

  def start_countdown(seconds)
    case self.state
    when "new", "active", "showed"
      self.transaction do
        self.section.active_question = self
        self.update_attributes :countdown_to => Time.now + seconds.to_i
      end
    end
  end

  def stop_countdown
    if self.stop_countdown?
      self.update_attributes :state => "statistics", :countdown_to => nil
      comet_section_question_changed self.section
    end
  end

  def stop_countdown?
    self.countdown_to and Time.now >= self.countdown_to
  end

  def countdown_remaining
    if self.countdown_to
      if self.stop_countdown?
        self.stop_countdown
        nil
      else
        (self.countdown_to - Time.now).round
      end
    else
      nil
    end
  end
  
  def switch_state
    case self.state
    when "new"
      self.section.showed_question = self
    when "showed"
      self.section.active_question = self
    when "active"
      self.update_attributes :state => "statistics", :countdown_to => nil
    when "statistics"
      self.update_attributes :state => "finished", :countdown_to => nil
    end
  end

  def reset_state
    self.transaction do
      Vote.delete_all :answer_variant_id => self.answer_variants.map(&:id)
      self.update_attributes :state => "new", :countdown_to => nil
    end
  end

  def answered?
    self.answer_variants.joins(:anonymouss).count > 0
  end

  def voted_anonymous_count
    Anonymous.joins(:answer_variants).where('answer_variants.question_id' => self.id).uniq.map(&:id).uniq.count
  end

  def formated_answer_variants
    sum = 0.0
    self.answer_variants.each do |aw|
      sum += aw.votes.sum(:vote).to_f
    end
    self.answer_variants.map do |aw|
      votes = aw.votes.sum(:vote).to_f
      { :text => aw.text,
        :percent => if sum > 0; then (votes / sum) * 100; else 0; end}
    end
  end

  def voted_variants(anonymous)
    self.answer_variants.joins(:votes => :anonymous).where("anonymous.id" => anonymous).uniq
  end

  def question_answered?(anonymous)
    self.voted_variants(anonymous).first != nil
  end

  def kinds
    Question.validators_on(:kind).select do |v|
      v.kind_of? ActiveModel::Validations::InclusionValidator
    end.first.options[:in].collect do |k|
      [k, I18n.translate(k)]
    end
  end

  def states
    Question.validators_on(:state).select do |v|
      v.kind_of? ActiveModel::Validations::InclusionValidator
    end.first.options[:in].collect do |k|
      [k, I18n.translate(k)]
    end
  end

  private

  def set_defaults
    self.state ||= "new"
    self.kind ||= "radio"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!, :except => [:show]
  before_filter :get_question, :except => [:new, :create]
  before_filter :stop_countdown_question, :except => [:new, :create]

  # GET /questions/1
  # GET /questions/1.json
  def show
    respond_to do |format|
      format.html do
        question_breadcrumb @question
        render
      end
      format.json do
        render :json => @question.as_json(:methods => [:countdown_remaining])
      end
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @section = Section.find(params[:section_id])
    when_section_owner @section, @section do
      @question = @section.questions.build
      respond_to do |format|
        format.html do
          question_breadcrumb @question
          render
        end
        format.json { render json: @question }
      end
    end
  end

  # GET /questions/1/edit
  def edit
    when_section_owner @question.section, @question.section do
      question_breadcrumb @question
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    section = Section.find(params[:section][:id])
    when_section_owner section, section do
      @question = section.questions.build(params[:question].except(:state, :id, :section_id, :created_at, :updated_at))

      respond_to do |format|
        if @question.save
          format.html { redirect_to @question, notice: 'Question was successfully created.' }
          format.json { render json: @question, status: :created, location: @question }
        else
          format.html { render action: "new" }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    section = @question.section
    when_section_owner section, section do
      respond_to do |format|
        if @question.update_attributes(params[:question].except(:state, :countdown_to, :id, :section_id, :created_at, :updated_at))
          format.html { redirect_to section, notice: 'Question was successfully updated.' }
          format.json { head :no_content }
          if ["active", "showed", "statistics"].include? @question.state
            comet_section_question_changed section
          end
        else
          format.html { render action: "edit" }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    section = Section.find(@question.section)
    update = ["active", "showed"].include? @question.state
    when_section_owner section, section do
      @question.destroy

      respond_to do |format|
        format.html { redirect_to section }
        format.json { head :no_content }
        comet_section_question_changed section if update
      end
    end
  end

  def switch_state
    when_section_owner @question.section do
      @question.switch_state
      respond_to do |format|
        format.html { redirect_to @question.section }
        format.json { head :no_content }
        if @question.state != "new"
          comet_section_question_changed @question.section
        end
      end
    end
  end

  def reset_state
    when_section_owner @question.section do
      update = ["showed", "active", "statistics"].include? @question.state
      @question.reset_state
      respond_to do |format|
        format.html { redirect_to @question.section }
        format.json { head :no_content }
        comet_section_question_changed @question.section if update
      end
    end
  end

  def start_countdown
    when_section_owner @question.section do
      @question.start_countdown Settings.questions.countdown_time #  FIXME: make it configurable
      respond_to do |format|
        format.html { redirect_to @question.section }
        format.json { head :no_content }
        comet_section_question_changed @question.section
      end
    end
  end

  private
  def get_question
    @question = Question.find(params[:id])
  end

  def stop_countdown_question
    @question.stop_countdown
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= fields_for @question.section do |sf| %>
    <%= sf.hidden_field :id %>
  <% end %>


  <div class="input-wrapper">
    <%= f.text_area :question, :placeholder => "Текст вопроса" %>
  </div>

  <div id="kind">
    <% @question.kinds.each do |id, txt| %>
    <label>
      <%= f.radio_button :kind, id %>
      <span title="<%= txt %>">
        <%= txt %>
      </span>
    </label>
    <% end %>
  </div>


<div style="clear: both;"></div>
<hr>
   <%= link_to (t "buttons.back"), @question.section, :class => "button"%>
   <%= f.submit (t "buttons.save"), :class => "button", :style => "float: right;" %>
<% end %>

app/views/questions/edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<div class="formHeader">Редактирование вопроса</div>

<%= render 'form' %>

app/views/questions/new.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>

<div class="formHeader">Новый вопрос</div>

<%= render 'form' %>

app/views/questions/show.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<p id="notice"><%= notice %></p>

<div class="formHeader"><%= @question.question %></div>

<p>
  <b>State:</b>
  <%= t @question.state %>
</p>

<p>
  <b>Kind:</b>
  <%= t @question.kind %>
</p>

<div class="formHeader">Варианты ответа</div>

<div id="sctn">
  <% @question.answer_variants.each do |answer_variant| %>
  <div class="name">
    <%= link_to answer_variant.text, answer_variant %>
    <div class="edit">
      <% if section_owner? @question.section %>
	     <%= link_to (raw "&uarr;"), bringup_answer_variant_path(answer_variant), :method => :post, :class => "small_button" %>
	     <%= link_to (raw "&darr;"), bringdown_answer_variant_path(answer_variant), :method => :post, :class => "small_button" %>
	     <%= link_to (t "buttons.edit"), edit_answer_variant_path(answer_variant), :class => "small_button" %>
	     <%= link_to (t "buttons.delete"), answer_variant, method: :delete, data: { confirm: 'Are you sure?' }, :class => "small_button" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>


<div style="clear: both;"></div>
<br />
<hr />
<div>
  <%= link_to (t "buttons.back"), @question.section, :class => "button" %>
  <% if section_owner? @question.section %>
    <%= link_to (t "buttons.edit"), edit_question_path(@question), :class => "button" %>
    <%= link_to (t "buttons.newAnswer"), new_question_answer_variant_path(@question), :class => "button", :style => "float: right;" %>
  <% end %>
</div>