config/routes.rb
Ruvote::Application.routes.draw do

  resources :screens, :only => [:show, :update] do
    member do
      get "banner"
      get "twitts"
      get "question"
    end
  end

  get "home" => 'static#home'
  get 'login/registration' => 'login#registration'
  get 'login/forgot_password' => 'login#forgot_password'
  get 'login/login' => 'login#login'

  resources :s, :only => [:show, :index] do
    member do 
      get 'twitt'
      get 'name'
      post 'set_name'
    end
  end

  resources :votes, :only => [] do
    collection do
      post 'radio'
      post 'check'
    end
  end

  resources :twitts, :only => [:create, :destroy]

  resources :answer_variants, :only => [:show, :edit, :create, :update, :destroy] do
    member do
      post 'bringup'
      post 'bringdown'
    end
  end

  resources :questions, :only => [:show, :edit, :create, :update, :destroy] do
    resources :answer_variants, :only => [:new]
    member do
      post "switch_state"
      post "reset_state"
      post "start_countdown"
    end
  end

  resources :sections, :only => [:show, :edit, :create, :update, :destroy] do
    resources :questions, :only => [:new]
    resource :section_statistics, :only => [:show]
    member do
      get 'twitts_edit'
      get 'twitts'
    end
    collection do
      post '/twitt/:twitt_id/activate' => 'sections#activate_twitt'
    end
  end

  resources :meetings do
    resources :sections, :only => [:new]
  end

  devise_for :users

  root :to => "static#home"

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :descr, :name
  has_many :sections, :dependent => :destroy
  belongs_to :user
  validates :name, :presence => true
  validates :name, :uniqueness => true 
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /meetings
  # GET /meetings.json
  def index
    if user_signed_in?
      @my_meetings = current_user.meetings
      @meetings = current_user.find_foreign
    else 
      @meetings = Meeting.all
    end
    meetings_breadcrumb
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
    meeting_breadcrumb @meeting

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new
    meeting_breadcrumb @meeting

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
    when_meeting_owner @meeting do 
      meeting_breadcrumb @meeting
    end
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = current_user.meetings.build(params[:meeting].except(:id, :user_id, :created_at, :updated_at))

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])
    when_meeting_owner @meeting do 
      respond_to do |format|
        if @meeting.update_attributes(params[:meeting].except(:id, :user_id, :created_at, :updated_at))
          format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @meeting.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    when_meeting_owner @meeting do 
      @meeting.destroy

      respond_to do |format|
        format.html { redirect_to meetings_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-wrapper">
       <%= f.text_field :name, :placeholder => "Название мероприятия" %>
  </div>
  <br />
  <div class="input-wrapper">
    <%= f.text_area :descr, :placeholder => "Описание мероприятия" %>
  </div>

<div style="clear: both;"></div>
<hr>
   <%= link_to (t "buttons.back"), meetings_path, :class => "button" %>
   <%= f.submit (t "buttons.save"), :class => "button right" %>
<% end %>

app/views/meetings/edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>

<div class="formHeader">Редактирование мероприятия</div>

<%= render 'form' %>

app/views/meetings/index.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>

<% if user_signed_in? %>
<div class="formHeader">Мои мероприятия</div>

<div id="mtng">
 <% @my_meetings.each do |meeting| %>
 <div class="mtng">
    <div class="name" style="width: 720px;"><%= link_to meeting.name, meeting %></div>
    <div class="date">27 - 28 ноября 2012</div>

    <div style="clear:both;"> </div>

<div>
    <div class="descr" style="width: 720px;"><%= meeting.descr %></div>
    <div class="edit">
	<%= link_to (t "buttons.edit"), edit_meeting_path(meeting), :class => "small_button" %>
	<%= link_to (t "buttons.delete"), meeting, method: :delete, data: { confirm: 'Удалить ?' }, :class => "small_button"%>
    </div>
</div>
 </div>
 <% end %>
 <div style="clear:both;"> </div>
</div>

<% end %>

<% if user_signed_in? %>
  <div class="formHeader">Все мерприятия</div>
<% else %>
  <div class="formHeader">Мероприятия</div>
<% end %>

<div id="mtng">
<% @meetings.each do |meeting| %>
    <div class="name"><%= link_to meeting.name, meeting %></div>
    <div style="clear:both;"> </div>
    <div class="descr"><%= meeting.descr %></div>
<% end %>
</div>

<hr>
<%= link_to (t "buttons.back"), meetings_path, :class => "button" %>
<%= link_to (t "buttons.create"), new_meeting_path, :class => "button right" %>

app/views/meetings/new.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<div class="formHeader">Создать мероприятие</div>

<%= render 'form' %>

app/views/meetings/show.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>

<p id="notice"><%= notice %></p>

<div id="mtng">
    <div class="name"><%= @meeting.name %></div>
    <div style="clear:both;"> </div>
    <div class="descr"><%= @meeting.descr %></div>
</div>

<div class="formHeader">Список секций</div>

<div id="sctn">
<% @meeting.sections.each do |section| %>
  <div class="name"><%= link_to section.name, section  %></div>
  <div class="descr"><%= section.descr %>
  <% if meeting_owner? @meeting %>
    <div class="edit">
	<%= link_to (t "buttons.edit"), edit_section_path(section), :class => "small_button" %>
	<%= link_to (t "buttons.delete"), section, method: :delete, data: { confirm: 'Удалить секцию ?' }, :class => "small_button"%>
    </div>
  <% end %>
  </div>
<% end %>
</div>
<div style="clear: both;"></div>
<br />

<div>
<hr>
  <%= link_to (t "buttons.back"), meetings_path, :class => "button" %>
  <% if meeting_owner? @meeting %>
    <%= link_to (t "buttons.edit"), edit_meeting_path(@meeting), :class => "button" %>
    <%= link_to (t "buttons.newSection"), new_meeting_section_path(@meeting), :class => "button right" %>
  <% end %>
</div>