config/routes.rb
Ruvote::Application.routes.draw do

  resources :screens, :only => [:show, :update] do
    member do
      get "banner"
      get "twitts"
      get "question"
    end
  end

  get "home" => 'static#home'
  get 'login/registration' => 'login#registration'
  get 'login/forgot_password' => 'login#forgot_password'
  get 'login/login' => 'login#login'

  resources :s, :only => [:show, :index] do
    member do 
      get 'twitt'
      get 'name'
      post 'set_name'
    end
  end

  resources :votes, :only => [] do
    collection do
      post 'radio'
      post 'check'
    end
  end

  resources :twitts, :only => [:create, :destroy]

  resources :answer_variants, :only => [:show, :edit, :create, :update, :destroy] do
    member do
      post 'bringup'
      post 'bringdown'
    end
  end

  resources :questions, :only => [:show, :edit, :create, :update, :destroy] do
    resources :answer_variants, :only => [:new]
    member do
      post "switch_state"
      post "reset_state"
      post "start_countdown"
    end
  end

  resources :sections, :only => [:show, :edit, :create, :update, :destroy] do
    resources :questions, :only => [:new]
    resource :section_statistics, :only => [:show]
    member do
      get 'twitts_edit'
      get 'twitts'
    end
    collection do
      post '/twitt/:twitt_id/activate' => 'sections#activate_twitt'
    end
  end

  resources :meetings do
    resources :sections, :only => [:new]
  end

  devise_for :users

  root :to => "static#home"

end

app/models/section.rb
class Section < ActiveRecord::Base
  attr_accessible :name, :anonymous_count, :descr, :screens_count
  has_many :questions, :dependent => :destroy
  has_many :anonymouss, :dependent => :destroy
  has_many :screens, :order => "id asc"
  belongs_to :meeting
  validates :name, :presence => true
  validates :name, :uniqueness => {:scope => :meeting_id}

  def screens_count
    self.screens.count
  end

  def screens_count=(count)
    count = count.to_i
    if count >= 0
      if self.screens_count < count
        (count - self.screens_count).times do
          self.screens.create
        end
      elsif self.screens_count > count
        self.screens.reorder("id desc").limit(self.screens_count - count).each do |s|
          s.destroy
        end
      end
    end
  end

  def answered_questions
    Enumerator.new do |en|
      self.questions.where(:state => 'finished').each do |question|
        if question.answered?
          en.yield question
        end
      end
    end
  end

  def formated_twitts
    Enumerator.new do |en|
      self.twitts.each do |twitt|
        ret =  {
          name:  twitt.anonymous.formated_name,
          text:  twitt.text,
          state: twitt.state,
        }
        en.yield ret
      end
    end
  end

  def formated_active_twitts
    Enumerator.new do |en|
      self.active_twitts.each do |twitt|
        ret = {
          name:  twitt.anonymous.formated_name,
          text:  twitt.text,
          state: twitt.state,
        }
        en.yield ret
      end
    end
  end
  
  def twitts
    Twitt.joins(:anonymous => :section).where('anonymous.fake' => false, 'sections.id' => self.id).reorder('twitts.created_at desc')
  end
  
  def active_twitts
    Twitt.joins(:anonymous => :section).where('anonymous.fake' => false, 'sections.id' => self.id, 'twitts.state' => "active").reorder('twitts.created_at desc')
  end

  def statistics_question
    self.questions.where(:state => "statistics").first
  end

  def current_question
    self.showed_question || self.active_question || self.statistics_question
  end

  def active_question
    self.questions.where(:state => "active").first
  end

  def active_question=(question)
    if question == nil
      self.transaction do
        self.questions.where(:state => "active").each do |q|
          q.update_attributes :state => "finished", :countdown_to => nil
        end
      end
    elsif question.section == self and question.state != "active"
      self.transaction do
        self.questions.where(:state => ["active", "showed", "statistics"]).each do |q|
          if q.id != question.id
            q.update_attributes :state => (q.state == "showed" ? "new" : "finished"), :countdown_to => nil
          end
        end
        question.update_attributes :state => "active"
      end
    end
  end

  def showed_question
    self.questions.where(:state => "showed").first
  end

  def showed_question=(question)
    if question == nil
      self.transaction do
        self.questions.where(:state => "showed").each do |q|
          q.update_attributes :state => "new", :countdown_to => nil
        end
      end
    elsif question.section == self and question.state != "showed"
      self.transaction do
        self.questions.where(:state => ["active", "showed", "statistics"]).each do |q|
          if q.id != question.id
            q.update_attributes :state => (q.state == "showed" ? "new" : "finished"), :countdown_to => nil
          end
        end
        question.update_attributes :state => "showed"
      end
    end
  end

  def anonymous_count=(need)
    need = need.to_i
    need = 0 if need < 0
    self.transaction do 
      active_count = self.anonymous_count
      all_count = self.anonymouss.where(:fake => false).count
      if active_count > need
        deactivate_anonymous active_count - need
      elsif active_count < need
        if all_count >= need
          activate_anonymous need - active_count
        else
          activate_anonymous all_count - active_count
          generate_anonymous need - all_count
        end
      end
    end
  end

  def anonymous_count
    self.anonymouss.where(:fake => false, :active => true).count
  end

  private
  def generate_anonymous(cnt)
    cnt.times do
      self.anonymouss.create
    end
  end

  def deactivate_anonymous(cnt)
    self.anonymouss.where(:fake => false, :active => true).reorder("id desc").limit(cnt).each do |x|
      x.update_attribute(:active, false)
    end
  end

  def activate_anonymous(cnt)
    self.anonymouss.where(:fake => false, :active => false).reorder("id asc").limit(cnt).each do |x|
      x.update_attribute(:active, true)
    end
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  include ApplicationHelper
  before_filter :authenticate_user!, :except => [:show, :twitts]

  def twitts_edit               #  FIXME: move to separate controller
    @section = Section.find(params[:id])
    when_section_owner @section, @section do
      section_breadcrumb @section
      add_breadcrumb (t 'sections.twitts-edit'), twitts_edit_section_path(@section)
    end
  end

  def twitts                    #  FIXME: move to separate controller
    @section = Section.find(params[:id])
    section_breadcrumb @section
    add_breadcrumb (t 'sections.twitts'), twitts_section_path(@section)
  end

  def activate_twitt            #  FIXME: move to separate controller
    twitt = Twitt.find(params[:twitt_id])
    when_section_owner twitt.anonymous.section do
      twitt.state = if twitt.state == "new"; then "active" else "new" end
      respond_to do |format|
        if twitt.save
          format.html {redirect_to twitts_edit_section_path(twitt.anonymous.section)}
          format.json {header :no_content}
          comet_section_twitts_activated twitt.anonymous.section
        else
          format.html {redirect_to twitts_edit_section_path(twitt.anonymous.section)}
          format.json {render :json => twitt.errors, :status => :unprocessable_entity}
        end
      end
    end
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @section = Section.find(params[:id])
    section_breadcrumb @section
    if @section.active_question
      @section.active_question.stop_countdown
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @section }
    end
  end

  # GET /sections/new
  # GET /sections/new.json
  def new
    @meeting = Meeting.find(params[:meeting_id])
    when_meeting_owner @meeting do
      @section = @meeting.sections.build
      section_breadcrumb @section

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @section }
      end
    end
  end

  # GET /sections/1/edit
  def edit
    @section = Section.find(params[:id])
    when_section_owner @section do
      section_breadcrumb @section
    end
  end

  # POST /sections
  # POST /sections.json
  def create
    meeting = Meeting.find(params[:meeting][:id])
    when_meeting_owner meeting, meeting do
      @section = meeting.sections.build(params[:section].except(:anonymous_count, :screens_count, :id, :meeting_id, :created_at, :updated_at))
      respond_to do |format|
        if @section.save
          @section.anonymous_count = params[:section][:anonymous_count] || 0
          @section.screens_count = params[:section][:screens_count] || 0
          format.html { redirect_to @section, notice: 'Section was successfully created.' }
          format.json { render json: @section, status: :created, location: @section }
          enqueue_archive_generation(@section)
        else
          format.html { render action: "new" }
          format.json { render json: @section.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /sections/1
  # PUT /sections/1.json
  def update
    @section = Section.find(params[:id])
    when_section_owner @section do
      respond_to do |format|
        if @section.update_attributes(params[:section].except(:id, :meeting_id, :created_at, :updated_at))
          format.html { redirect_to @section, notice: 'Section was successfully updated.' }
          format.json { head :no_content }
          remove_section_archive(@section)
          enqueue_archive_generation(@section)
        else
          format.html { render action: "edit" }
          format.json { render json: @section.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section = Section.find(params[:id])
    when_section_owner @section do
      meeting = Meeting.find(@section.meeting)
      @section.destroy

      respond_to do |format|
        format.html { redirect_to meeting }
        format.json { head :no_content }
        remove_section_archive(@section)
      end
    end
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-wrapper">
        <%= f.text_field :name, :placeholder => "Название секции" %>
  </div>
  <br />
    <div class="input-wrapper">
        <%= f.text_area :descr, :placeholder => "Описание секции, тезисы" %>
  </div>
  <%= fields_for @section.meeting do |mf| %>
    <%= mf.hidden_field :id %>
  <% end %>
<br />
  <div class="input-wrapper-num">
    <%= f.label :anonymous_count, "Количество участников секции" %>: <%= f.number_field :anonymous_count, :min => 0, :max => 5000, :step => 10 %>
  </div>
  <div class="input-wrapper-num">
    <%= f.label :screens_count, "Количество экранов для вывода результатов" %>: <%= f.number_field :screens_count, :min => 0, :max => 1000, :step => 1 %>
  </div>
<hr>
  <div class="actions">
    <%= link_to (t "buttons.back"), @section.meeting, :class => "button" %>
    <%= f.submit (t "buttons.save"), :class => "button right" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<div class="formHeader">Редактирование секции</div>

<%= render 'form' %>

<!--
< %= link_to 'Show', @section %> |
< %= link_to 'Back', @section.meeting %> -->

app/views/sections/new.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<div class="formHeader">Новая секция</div>

<%= render 'form' %>

<!-- < %= link_to 'Back', @meeting %> -->

app/views/sections/show.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag "application/sections" %>
<%= javascript_include_tag "application/application" %>
<% end %>


<%= javascript_tag do %>
  $(function() {
  $('.screen_state_select').change(
  function(){
  $(this).closest('form').trigger('submit');
  })});
<% end %>

<p id="notice"><%= notice %></p>
<table>
<tr>
  <td style="width: 815px;" >
    <div id="mtng">
	<div class="name"><%= @section.name %></div>
	<div style="clear:both;"> </div>
	<div class="descr"><%= @section.descr %></div>
    </div>
  </td>

  <td>
    <div>
      <div>
	<%= t "anonymous_count" %> <b><%= @section.anonymous_count %></b>
      </div>
      <div>
        <% if section_owner? @section %>
	      <%= link_to (t 'sections.archive'), section_archive_path(@section) %>
        <% end %>
      </div>
    </div>
  </td>
</tr>
</table>
<hr> <!-- --------------------------------------------------------------------------------------------------- -->
<table border="0" style="width:100%;">
<tr style="height: 60px;">
  <td style="width:50%;">
  <br />
  <% if section_owner? @section %>
    <% @section.screens.each_with_index do |screen, idx| %>
      <div class="screen-mosaic">
        <div class="screen-block-element">
          Экран <%= "№ #{idx + 1}" %>
        </div>
        <div class="screen-block-element">
        <%= form_for screen do |f| %>
          <%= f.select :state, screen.rev_states, {}, {:title => "", :class => "screen_state_select"} %>
        <% end %>
        </div>
        <div class="screen-block-element">
          <%= link_to (t 'buttons.show'), screen, :class => "small_button", :title => "'Экран' откроется в новом окне", :style => "display: inline", :target => "_blank" %>
        </div>
      </div>
    <% end %>
    <br />
    <% end %>
  </td>
  <td>
      <div class="right">
	  <% if section_owner? @section %>
	    <%= link_to (t 'buttons.moderate'), twitts_edit_section_path(@section), :title => "Показать или скрыть сообщения чата", :class => "small_button"%>
	  <% end %>
	  <%= link_to (t 'buttons.showStatistic'), section_section_statistics_path(@section), :title => "Отобразить статистику по всем вопросам", :class => "small_button" %>
      </div>
  </td>
</tr>
</table>
<hr> <!-- --------------------------------------------------------------------------------------------------- -->
<div class="formHeader"><%= t "sections.questions" %></div>

<div id="sctn">
<% @section.questions.each do |question| %>
  <div class="name"><%= link_to question.question, question %></div>
  <div class="descr"><%= t question.state %>, <%= t question.kind %>
    <% if section_owner? @section %>
      <div class="edit">
        <% case question.state %>
        <% when "new" %>
          <%= link_to (t "buttons.show"), switch_state_question_path(question), :title => "Отобразить вопрос на 'Экран'", :method => :post, :class => "small_button" %>
        <% when "showed" %>
          <%= link_to (t "buttons.start-countdown"), start_countdown_question_path(question), :title => "Начать голосование с таймером", :method => :post, :class => "small_button" %>
          <%= link_to (t "buttons.start-vote"), switch_state_question_path(question), :title => "Начать голосование", :method => :post, :class => "small_button" %>
        <% when "active" %>
          <%= link_to (t "buttons.show-results"), switch_state_question_path(question), :title => "Завершить сбор голосов. Отобразить результаты на 'Экране'", :method => :post, :class => "small_button" %>
        <% when "statistics" %>
          <%= link_to (t "buttons.finish"), switch_state_question_path(question), :title => "Скрыть результаты. Закрыть вопрос", :method => :post, :class => "small_button" %>
        <% end %>

        <% if ["showed", "active", "statistics", "finished"].include? question.state %>
          <%= link_to (t "buttons.reset"), reset_state_question_path(question), :title => "Обнулить результаты. Перевести вопрос в статус 'Новый'", :method => :post, :data => {:confirm => "Все голоса участников будут удалены, продолжить ?"}, :class => "small_button" %>
        <% end %>
        
	    <%= link_to (t "buttons.edit"), edit_question_path(question), :title => "Редактировать вопрос и его тип", :class => "small_button" %>
	    <%= link_to (t "buttons.delete"), question, method: :delete, data: { confirm: 'Удалить вопрос?' }, :class => "small_button" %>
      </div>
    <% end %>
  </div>
<% end %>
</div>

<div style="clear: both;"></div>
<br />
<hr />
  <%= link_to (t "buttons.back"), @section.meeting, :class => "button" %>
  <% if section_owner? @section %>
    <%= link_to (t "buttons.edit"), edit_section_path(@section), :class => "button" %>
    <%= link_to (t "buttons.create"), new_section_question_path(@section), :class => "button", :style => "float: right;" %>
  <% end %>


<!--
< %= link_to (t :edit), edit_section_path(@section) %> |
 -->

app/views/sections/twitts.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>


<table id="twittTable">
  <% @section.active_twitts.limit(20).each do |twitt| %>
<tr>
  <td>
    <b><%= twitt.anonymous.formated_name %></b>:
    <div class="tableMsg"><%= twitt.text%></div>
  <td/>
<tr/>
  <% end %>
</tr>
</table>

app/views/sections/twitts_edit.html.erb
<% content_for :head do %>
<%= javascript_include_tag "application/application" %>
<% end %>

<table id="twittTable">
  <tr>
    <th class="roundedleft">Статус</th>
    <th class="roundedright">Сообщение</th>
  </tr>
  <% @section.twitts.each do |twitt| %>
  <tr>
    <% if twitt.state == "new" %>
     <td class="tableStat"><%= link_to " ", activate_section_twitt(twitt), :title => "Скрыто. Нажмите чтобы показать", :method => :post, :class => "cansel_button" %></td>
     <td>
	<b><%= twitt.anonymous.formated_name %></b>:
	<div class="tableMsg"><%= twitt.text%></div>
    </td>
    <% else  %>
      <td class="tableStat"><%= link_to " ", activate_section_twitt(twitt), :title => "Отображается. Нажмите что быскрыть", :method => :post, :class => "active_button" %></td>
      <td>
	<b><%= twitt.anonymous.formated_name %></b>:
	<div class="tableMsg"><%= twitt.text%></div></td>
      </td>
    <% end %>
  </tr>
  <% end %>
</table>